from mypy_boto3_macie.type_defs import (
    ClassificationTypeTypeDef,
    ClassificationTypeUpdateTypeDef,
    FailedS3ResourceTypeDef,
    MemberAccountTypeDef,
    S3ResourceClassificationTypeDef,
    S3ResourceTypeDef,
    AssociateS3ResourcesResultTypeDef,
    DisassociateS3ResourcesResultTypeDef,
    ListMemberAccountsResultTypeDef,
    ListS3ResourcesResultTypeDef,
    PaginatorConfigTypeDef,
    S3ResourceClassificationUpdateTypeDef,
    UpdateS3ResourcesResultTypeDef,
)

__all__ = (
    "ClassificationTypeTypeDef",
    "ClassificationTypeUpdateTypeDef",
    "FailedS3ResourceTypeDef",
    "MemberAccountTypeDef",
    "S3ResourceClassificationTypeDef",
    "S3ResourceTypeDef",
    "AssociateS3ResourcesResultTypeDef",
    "DisassociateS3ResourcesResultTypeDef",
    "ListMemberAccountsResultTypeDef",
    "ListS3ResourcesResultTypeDef",
    "PaginatorConfigTypeDef",
    "S3ResourceClassificationUpdateTypeDef",
    "UpdateS3ResourcesResultTypeDef",
)
